### ISSUE TITLE
Regarding OFA Implementation for Other Networks and Object Detection

### ISSUE THREAD

**Issue by Darshcg** [PaddlePaddle/PaddleSlim#775]
Hi,

I have explored about Once For All Network for MobileNetv1. I felt it very interesting and want to work on Implementing it for Other Networks and for Object Detection tasks. Can anyone please guide me with the same, how do I proceed if I want to Implement this for Other Networks and Object Detection Task?

Looking forward to hearing from you

Best Regards,
Darshan C G,

**Comment by ceci3** [comment]
We are trying to implement Once For All in another network, like yolo in Object Detection。
The basic way to implement this way to other network is :
1. Have a pre-trained model first. 
2. Convert the pre-trained model to supermodel, by using Convert, supernet in paddleslim.nas.ofa.convert_super, like: https://github.com/PaddlePaddle/PaddleSlim/blob/develop/demo/ofa/bert/run_glue_ofa.py#L387
3. Pre-trained model in 1 define as the teacher model.
4. train elastic model.

The full step and effect can reference to the step in bert code: https://github.com/PaddlePaddle/PaddleSlim/blob/develop/demo/ofa/bert/run_glue_ofa.py#L382

**Comment by Darshcg** [comment]
Thank you very much @ceci3 and @wanghaoshuang for your kind reply.

I have got a clearer idea of the implementation.

I want to apply OFA Technique for Object Detection Networks like Yolo, Retinanet, and other Networks for Face Detection like Retinaface.
Having said that I was having a doubt regarding converting the ordinary Network to Supernet.

The figure below is a Basic Object Detection Pipeline:
![image](https://user-images.githubusercontent.com/48723743/119630067-37446600-be2c-11eb-8aa3-616bf8bd09b4.png)

Parts from the Above Pipeline: **Backbone, Neck, Dense Prediction, Sparse Prediction.**

So, while converting from Ordinary Network to Supernet, which all part of the above pipeline will be converted? Whether some parts will be converted(like only Backbone, or only Backbone and Neck) or all the parts will be converted(Backbone, Neck, Dense Prediction, Sparse Prediction)? how to decide on this?

Looking forward to your reply.

Thanks,
Darshan

**Comment by ceci3** [comment]
Haha, we are also trying to find which method will be better for the series of Yolo. We tried to convert the backbone-only or backbone+neck or neck-only to Supernet, but there is no comprehensive conclusion yet.  Do you have any ideas about this? We will keep trying in the near future.  We can discuss the ofa+detection together~
I think that convert all the parts should be feasible because supernet training is equivalent to re-modifying the distribution of the parameters in the network, the parameters after training are more suitable for the method of selecting sub-models from the supernet.


Looking forward to your reply~
Thanks,
Ceci

**Comment by ceci3** [comment]
@Darshcg We also trying to find which method will be better for the series of Yolo. We tried to convert the backbone-only or backbone+neck or neck-only to Supernet, but there is no comprehensive conclusion yet. Do you have any ideas about this? We will keep trying in the near future. We can discuss the ofa+detection together~
I think that convert all the parts should be feasible because supernet training is equivalent to re-modifying the distribution of the parameters in the network, the parameters after training are more suitable for the method of selecting sub-models from the supernet.

Looking forward to your reply~
Thanks,
Ceci
